MMM.xcodeproj/project.pbxproj, MMM/Resources/Base/AddImageView.swift, MMM/Resources/Base/SnackView.swift, MMM/Resources/Base/ToastView.swift, MMM/Resources/Extensions/Ex+UIView.swift, MMM/Resources/Info/Info.plist, MMM/Sources/ViewController/Add/AddDetailViewController.swift, MMM/Sources/ViewController/Home/HomeViewController.swift, MMM/Sources/ViewController/HomeDetail/DetailViewController.swift, MMM/Sources/ViewController/HomeDetail/EditActivityViewController.swift, MMM/Sources/ViewController/Profile/ViewController/ProfileViewController.swift, MMM/Sources/ViewController/Splash/SplashViewController.swift, MMM/Sources/ViewController/TabBar/CustomTabBar.swift, MMM/Sources/ViewController/TabBar/TabBarController.swift, MMM/Sources/ViewModels/EditActivityViewModel.swift, MMM/Sources/ViewModels/HomeDetailViewModel.swift
=> [Feat] 토스트 메시지 추가 및 오류 수정

MMM.xcodeproj/project.pbxproj, MMM/Resources/Base/SnackView.swift, MMM/Sources/ViewController/Home/HomeViewController.swift, MMM/Sources/ViewController/Home/LoadingViewController.swift, MMM/Sources/ViewController/HomeDetail/DetailViewController.swift, MMM/Sources/ViewController/Profile/ViewController/DataExportViewController.swift, MMM/Sources/ViewController/Profile/ViewController/ServiceViewController.swift, MMM/Sources/ViewController/Profile/ViewController/WithdrawViewController.swift, MMM/Sources/ViewController/TabBar/TabBarController.swift, MMM/Sources/ViewModels/HomeViewModel.swift, MMM/Sources/ViewModels/ProfileViewModel.swift
🌱 작업한 내용
- Test flight - network
- Resolved: #
=> [Chore] Test flight - network

MMM/App/SceneDelegate.swift, MMM/Resources/Base/StarPickerViewController.swift, MMM/Resources/Extensions/Ex+Publisher.swift, MMM/Resources/Extensions/Ex+UITextField.swift, MMM/Sources/Utilities/Tracking.swift, MMM/Sources/ViewController/Add/AddDetailViewController.swift, MMM/Sources/ViewController/Add/AddViewController.swift, MMM/Sources/ViewController/Home/DatePickerViewController.swift, MMM/Sources/ViewController/Home/HighlightViewController.swift, MMM/Sources/ViewController/Home/HomeFilterViewController.swift, MMM/Sources/ViewController/Home/HomeViewController.swift, MMM/Sources/ViewController/Onboarding/OnboardingViewController.swift, MMM/Sources/ViewController/TabBar/CustomTabBar.swift, MMM/Sources/ViewController/TabBar/TabBarController.swift, MMM/Sources/ViewModels/EditActivityViewModel.swift
=> [Feat] GA 완료

MMM/Resources/Base/BaseAddActivityViewController.swift, MMM/Sources/ViewController/Add/AddViewController.swift, MMM/Sources/ViewController/HomeDetail/DetailViewController.swift, MMM/Sources/ViewController/Onboarding/OnboardingViewController.swift
🌱 작업한 내용
- Onboarding
- Resolved: #70
=> [Feat] Onboarding

MMM.xcodeproj/project.pbxproj, MMM/Resources/Extensions/Ex+Window.swift, MMM/Resources/Info/Info.plist, MMM/Sources/ViewController/Home/HomeViewController.swift, MMM/Sources/ViewController/HomeDetail/DetailViewController.swift, MMM/Sources/ViewController/HomeDetail/EditActivityViewController.swift, MMM/Sources/ViewController/Profile/ViewController/DataExportViewController.swift, MMM/Sources/ViewController/Profile/ViewController/WithdrawViewController.swift, MMM/Sources/ViewController/TabBar/TabBarController.swift, MMM/Sources/ViewModels/EditActivityViewModel.swift, MMM/Sources/ViewModels/HomeViewModel.swift
=> [Feat] UI 기기 대응

MMM.xcodeproj/project.pbxproj, MMM/App/AppDelegate.swift, MMM/MMM.entitlements, MMM/Resources/Extensions/Ex+UITabBar.swift, MMM/Resources/Info/Info.plist, MMM/Sources/ViewController/Home/HomeViewController.swift, MMM/Sources/ViewController/Profile/ViewController/ProfileViewController.swift, MMM/Sources/ViewController/Profile/ViewController/PushSettingViewController.swift, MMM/Sources/ViewController/TabBar/TabBarController.swift, Podfile, Podfile.lock
=> [Feat] 탭바 & 알림 UI

MMM/Sources/Models/EconomicActivity.swift, MMM/Sources/ViewController/Statistics/StatisticsViewController.swift, MMM/Sources/ViewController/Statistics/Views/StatisticsActivityTableViewCell.swift, MMM/Sources/ViewController/Statistics/Views/StatisticsCategoryView.swift, Podfile, Podfile.lock
🌱 작업한 내용
- Slide text animation
- Resolved: #89
=> [Feat] Slide text animation

MMM/Sources/ViewController/Statistics/Views/StatisticsCategoryView.swift
🌱 작업한 내용
- (임시) 통계 Bar chart
- Resolved: #
=> [Feat] 통계 카테고리 Bar chart

MMM.xcodeproj/project.pbxproj, MMM/Sources/ViewController/Category/CategoryViewController.swift, MMM/Sources/ViewController/Category/Views/CategorySegmentedControl.swift, MMM/Sources/ViewController/Statistics/StatisticsViewController.swift, MMM/Sources/ViewController/Statistics/Views/StatisticsActivityView.swift, MMM/Sources/ViewController/TabBar/TabBarController.swift
🌱 작업한 내용
- Segmented control과 page control 결합
- Resolved: #
=> [Feat] Segmented control

MMM/Sources/ViewController/Statistics/StatisticsViewController.swift, MMM/Sources/ViewController/Statistics/Views/StatisticsActivityView.swift
- Timer를 DispatchSourceTimer로 변경
🌱 작업한 내용
- Timer로 selectRow가 실행되어 앱이 종료되는 문제 해결
- Resolved: #101
=> [Hotfix] Timer로 selectRow가 실행되어 앱이 종료되는 문제 해결

MMM/Sources/Reactor/BottomSheetReactor.swift, MMM/Sources/Services/Network/MMMAPIService.swift, MMM/Sources/ViewController/Home/DatePicker2ViewController.swift, MMM/Sources/ViewController/Profile/PushSettingDetailViewController.swift
🌱 작업한 내용
- Merge후 Code error 해결
- Resolved: #107
=> [Hotfix] Merge후 Code error 해결

MMM.xcodeproj/project.pbxproj, MMM/Resources/Assets/Icon.xcassets/iconMinus16.imageset/Contents.json, MMM/Resources/Assets/Icon.xcassets/iconPlus16.imageset/Contents.json, MMM/Resources/Extensions/Ex+UICollectionView.swift, MMM/Resources/Extensions/Ex+UIImage.swift, MMM/Resources/Extensions/Ex+UITextField.swift, MMM/Sources/Models/CategoryEdit.swift, MMM/Sources/Models/CategoryEditSectionModel.swift, MMM/Sources/Reactor/BottomSheet/CategoryEditBottomSheetReactor.swift, MMM/Sources/Reactor/CategoryEditCollectionViewCellReactor.swift, MMM/Sources/Reactor/CategoryEditReactor.swift, MMM/Sources/Reactor/CategoryReactor.swift, MMM/Sources/Services/CategoryProvider.swift, MMM/Sources/Services/ServiceProvider.swift, MMM/Sources/ViewController/BottomSheet/CategoryEditBottomSheetViewController.swift, MMM/Sources/ViewController/BottomSheet/TextFieldEditBottomSheetViewController.swift, MMM/Sources/ViewController/Category/CategoryContentViewController.swift, MMM/Sources/ViewController/Category/CategoryViewController.swift, MMM/Sources/ViewController/Category/Views/CategorySectionHeader.swift, MMM/Sources/ViewController/CategoryEdit/CategoryEditViewController.swift, MMM/Sources/ViewController/CategoryEdit/Views/CategoryEditCollectionViewCell.swift, MMM/Sources/ViewController/CategoryEdit/Views/CategoryEditSectionFooter.swift, MMM/Sources/ViewController/CategoryEdit/Views/CategoryEditSectionHeader.swift
🌱 작업한 내용
- 카테고리 편집
- Resolved: #
=> [Feat] 카테고리 편집 디테일 부분

MMM.xcodeproj/project.pbxproj, MMM/Sources/Models/CategoryHeader.swift, MMM/Sources/Reactor/BottomSheet/CategoryEditBottomSheetReactor.swift, MMM/Sources/Reactor/CategoryEditCollectionViewCellReactor.swift, MMM/Sources/Reactor/CategoryEditReactor.swift, MMM/Sources/Services/CategoryProvider.swift, MMM/Sources/ViewController/BottomSheet/CategoryAddBottomSheetViewController.swift, MMM/Sources/ViewController/BottomSheet/CategoryEditBottomSheetViewController.swift, MMM/Sources/ViewController/Category/CategoryDetailViewController.swift, MMM/Sources/ViewController/CategoryEdit/CategoryEditViewController.swift, MMM/Sources/ViewController/CategoryEdit/Views/CategoryEditCollectionViewCell.swift, MMM/Sources/ViewController/CategoryEdit/Views/CategoryEditSectionFooter.swift
🌱 작업한 내용
- 카테고리 삭제 및 추가 기능
- Resolved: #
=> [Feat] 카테고리 편집 기능(삭제, 추가)

MMM/Resources/Configuration/Constants.swift, MMM/Sources/ViewController/Profile/PushSettingDetailViewController.swift, MMM/Sources/ViewController/Profile/PushSettingViewController.swift, MMM/Sources/ViewController/Profile/Views/PushSetting/CustomPushTimeSettingView.swift, MMM/Sources/ViewController/Profile/Views/PushSetting/Week/WeekCollectionViewCell.swift
=> [Feat] local push 하는중

MMM/App/AppDelegate.swift, MMM/Resources/Configuration/Constants.swift, MMM/Resources/Extensions/Ex+Date.swift, MMM/Sources/Reactor/BottomSheet/CustomPush/CustomPushTextSettingReactor.swift, MMM/Sources/Reactor/PushSettingDetailReactor.swift, MMM/Sources/Reactor/PushSettingReactor.swift, MMM/Sources/ViewController/BottomSheet/CustomPush/CustomPushTextSettingViewController.swift, MMM/Sources/ViewController/BottomSheet/DateBottomSheetViewController.swift, MMM/Sources/ViewController/Profile/PushSettingDetailViewController.swift, MMM/Sources/ViewController/Profile/PushSettingViewController.swift, MMM/Sources/ViewController/Profile/Views/PushSetting/CustomPushTextSettingView.swift, MMM/Sources/ViewController/Profile/Views/PushSetting/CustomPushTimeSettingView.swift, MMM/Sources/ViewController/Profile/Views/PushSetting/DetailTimeSettingView.swift, MMM/Sources/ViewController/Profile/Views/PushSetting/Week/WeekCollectionViewCell.swift
=> [Feat] 로컬 푸쉬 기능

MMM.xcodeproj/project.pbxproj, MMM/Sources/Models/CategoryEdit.swift, MMM/Sources/Models/CategoryEditSectionModel.swift, MMM/Sources/Models/Requests/CategoryEditReqDto.swift, MMM/Sources/Models/Responses/CategoryEditResDto.swift, MMM/Sources/Reactor/Category/CategoryDetailReactor.swift, MMM/Sources/Reactor/Category/CategoryEditReactor.swift, MMM/Sources/Reactor/Category/CategoryEditUpperReactor.swift, MMM/Sources/Reactor/Category/CategoryMainReactor.swift, MMM/Sources/Services/CategoryProvider.swift, MMM/Sources/Services/Network/APIType.swift, MMM/Sources/Services/Network/MMMAPIService.swift, MMM/Sources/ViewController/BottomSheet/CategoryEditBottomSheetViewController.swift, MMM/Sources/ViewController/BottomSheet/CategoryEditUpperBottomSheetViewController.swift, MMM/Sources/ViewController/Category/CategoryContentViewController.swift, MMM/Sources/ViewController/Category/CategoryDetailViewController.swift, MMM/Sources/ViewController/Category/CategoryMainViewController.swift, MMM/Sources/ViewController/Category/Views/CategoryCollectionViewCell.swift, MMM/Sources/ViewController/Category/Views/CategorySectionGlobalHeader.swift, MMM/Sources/ViewController/CategoryEdit/CategoryEditUpperViewController.swift, MMM/Sources/ViewController/CategoryEdit/CategoryEditViewController.swift, MMM/Sources/ViewController/CategoryEdit/Views/CategoryEditDragCollectionViewCell.swift, MMM/Sources/ViewController/CategoryEdit/Views/CategoryEditTableViewCell.swift
🌱 작업한 내용
- Drag & Drop 에러 해결
- Resolved: #
=> [Feat] 카테고리 Drag drop

MMM.xcodeproj/project.pbxproj, MMM/Sources/Models/CategoryEditSectionModel.swift, MMM/Sources/Models/CategoryMainSectionModel.swift, MMM/Sources/Reactor/Category/CategoryDetailReactor.swift, MMM/Sources/Reactor/Category/CategoryEditReactor.swift, MMM/Sources/Reactor/Category/CategoryEditUpperReactor.swift, MMM/Sources/Reactor/Category/CategoryMainReactor.swift, MMM/Sources/Reactor/StatisticsReactor.swift, MMM/Sources/Services/Network/MMMAPIService.swift, MMM/Sources/ViewController/Category/CategoryContentViewController.swift, MMM/Sources/ViewController/Category/CategoryMainViewController.swift, MMM/Sources/ViewController/Category/Views/CategoryEmptyCollectionViewCell.swift, MMM/Sources/ViewController/Category/Views/CategorySectionHeader.swift, MMM/Sources/ViewController/CategoryEdit/CategoryEditViewController.swift, MMM/Sources/ViewController/CategoryEdit/Views/CategoryEditEmptyCollectionViewCell.swift, MMM/Sources/ViewController/Statistics/StatisticsViewController.swift, MMM/Sources/ViewModels/OnboardingViewModel.swift
🌱 작업한 내용
- 카테고리 Drag and drop 버그 해결
- Error 처리
- Empty Case 처리
- Resolved: #
=> [Fix] 카테고리 Drag and drop

MMM.xcodeproj/project.pbxproj, MMM/Resources/Assets/Icon.xcassets/iconCheckGray16.imageset/Contents.json, MMM/Resources/Assets/Icon.xcassets/iconCheckGray16.imageset/iconCheckGray16.svg, MMM/Resources/Assets/Icon.xcassets/iconCheckWhite16.imageset/Contents.json, MMM/Resources/Assets/Icon.xcassets/iconCheckWhite16.imageset/iconCheckWhite16.svg, MMM/Resources/Base/BaseAddActivityViewController.swift, MMM/Resources/Extensions/Ex+Icon.swift, MMM/Sources/Models/Responses/SelectDetailResDto.swift, MMM/Sources/Services/APIParameters.swift, MMM/Sources/ViewController/Add/AddDetailViewController.swift, MMM/Sources/ViewController/Category/CategoryMainViewController.swift, MMM/Sources/ViewController/CategoryEdit/CategoryEditViewController.swift, MMM/Sources/ViewController/ETC./AddCategoryView.swift, MMM/Sources/ViewController/HomeDetail/AddCategoryViewController.swift, MMM/Sources/ViewController/HomeDetail/DetailViewController.swift, MMM/Sources/ViewController/HomeDetail/EditActivityViewController.swift, MMM/Sources/ViewController/HomeDetail/Views/CategorySelectCell.swift, MMM/Sources/ViewController/HomeDetail/Views/CategorySelectHeaderCell.swift, MMM/Sources/ViewController/Profile/PushSettingDetailViewController.swift, MMM/Sources/ViewModels/AddCategoryViewModel.swift, MMM/Sources/ViewModels/EditActivityViewModel.swift
=> [Feat] 카테고리 편집 UI

MMM.xcodeproj/project.pbxproj, MMM/Sources/Reactor/Category/CategoryEditReactor.swift, MMM/Sources/Reactor/Category/CategoryEditUpperReactor.swift, MMM/Sources/ViewController/Category/CategoryContentViewController.swift, MMM/Sources/ViewController/CategoryEdit/CategoryEditUpperViewController.swift, MMM/Sources/ViewController/CategoryEdit/CategoryEditViewController.swift, MMM/Sources/ViewController/CategoryEdit/Views/CategoryEditSectionGlobalFooter.swift
🌱 작업한 내용
- 플로팅 버튼으로인한 Collection이 가려지는 문제 해결
- 빈 카테고리 끼리 Cell을 Drag & Drop할때 UI가 업데이트 되지 않는 문제 해결
- Resolved: #
=> [Fix] 카테고리 편집 버그 수정

MMM/Sources/ViewController/BottomSheet/CategoryAddBottomSheetViewController.swift, MMM/Sources/ViewController/BottomSheet/CategoryAddUpperBottomSheetViewController.swift, MMM/Sources/ViewController/BottomSheet/CategoryEditBottomSheetViewController.swift, MMM/Sources/ViewController/BottomSheet/CategoryEditUpperBottomSheetViewController.swift, MMM/Sources/ViewController/Statistics/Views/StatisticsCategoryView.swift
🌱 작업한 내용
- TextField 글자수 제한
- 카테고리 Bar 넓이 및 색상 조절
- Resolved: #
=> [Fix] Text field 글자 수 제한 및 테스트 플라이트 버그 해결

MMM/Sources/ViewController/CategoryEdit/Views/CategoryEditEmptyCollectionViewCell.swift, MMM/Sources/ViewController/Statistics/Views/StatisticsTitleView.swift
🌱 작업한 내용
- 통계에 이미지와 글이 안보이는 문제 해결
- Resolved: #
=> [Fix] 통계 UI 버그

MMM/Resources/Base/BaseAddActivityViewController.swift, MMM/Resources/Extensions/Ex+Publisher.swift, MMM/Sources/Reactor/PushSettingReactor.swift, MMM/Sources/ViewController/Add/AddDetailViewController.swift, MMM/Sources/ViewController/BottomSheet/CustomPush/CustomPushTextSettingViewController.swift, MMM/Sources/ViewController/HomeDetail/AddCategoryViewController.swift, MMM/Sources/ViewController/HomeDetail/EditActivityViewController.swift, MMM/Sources/ViewController/HomeDetail/Views/CategorySelectCell.swift, MMM/Sources/ViewController/Profile/PushSettingDetailViewController.swift, MMM/Sources/ViewController/Profile/PushSettingViewController.swift
=> [Feat] 버그 픽스픽스

MMM.xcodeproj/project.pbxproj, MMM/Sources/Models/Requests/WidgetReqDto.swift, MMM/Sources/Models/Responses/WidgetResDto.swift, MMM/Sources/Reactor/Category/CategoryEditReactor.swift, MMM/Sources/Services/APIRouter.swift, MMM/Sources/Services/Network/APIType.swift, MMM/Sources/Services/Network/MMMAPIService.swift, MMM/Sources/ViewController/CategoryEdit/CategoryEditViewController.swift, MMM/Sources/ViewController/Home/HomeViewController.swift, MMM/Sources/ViewController/HomeDetail/DetailViewController.swift, MMM/Sources/ViewController/Statistics/Views/StatisticsActivityView.swift, MMM/Sources/ViewModels/HomeDetailViewModel.swift, MMM/Sources/ViewModels/HomeViewModel.swift
🌱 작업한 내용
- 카테고리 Drag & Drop 개선
- Resolved: #
=> [Fix] 카테고리 Drag & Drop 개선

MMM.xcodeproj/project.pbxproj, MMM/Sources/Reactor/BottomSheet/StatisticsDateBottomSheetReactor.swift, MMM/Sources/ViewController/BottomSheet/StatisticsDateBottomSheetViewController.swift, MMM/Sources/ViewController/Home/HomeViewController.swift, MMM/Sources/ViewController/HomeDetail/DetailViewController.swift, MMM/Sources/ViewController/Statistics/StatisticsViewController.swift, MMM/Sources/ViewModels/OnboardingViewModel.swift
🌱 작업한 내용
- 아이디가 공유되는 문제 해결
- 위젯이 바뀌는 시점 변경
- 1초뒤 Loading 및 데이터 통신
- Date Provier가 공유되어 있는 문제 해결
- Resolved: #
=> [Fix] 배포전 버그 수정

MMM/Resources/Extensions/Ex+Date.swift, MMM/Resources/Extensions/Ex+String.swift, MMM/Sources/ViewController/BottomSheet/DateBottomSheetViewController.swift, MMM/Sources/ViewController/Profile/PushSettingDetailViewController.swift
=> Feat/133 bug fix/bug fix

MMM/Sources/Models/Responses/StatisticsResDto.swift, MMM/Sources/Reactor/Category/CategoryEditReactor.swift, MMM/Sources/Reactor/StatisticsReactor.swift, MMM/Sources/ViewController/CategoryEdit/CategoryEditViewController.swift, MMM/Sources/ViewController/Challenge/ChallengeViewController.swift, MMM/Sources/ViewController/Statistics/Views/StatisticsActivityView.swift
🌱 작업한 내용
- Drag & Drop 최적화
- Pagenation 오류 해결
- 챌린지 View UI 변경
- 통계의 Label 이 잘리는 현상 해결
- Resolved: #
=> [Fix] Before distribution

MMM/Resources/Configuration/Constants.swift, MMM/Sources/Reactor/Category/CategoryDetailReactor.swift, MMM/Sources/Reactor/StatisticsReactor.swift, MMM/Sources/ViewController/Add/AddDetailViewController.swift, MMM/Sources/ViewController/Add/AddViewController.swift, MMM/Sources/ViewController/Category/CategoryDetailViewController.swift, MMM/Sources/ViewController/Challenge/ChallengeViewController.swift, MMM/Sources/ViewController/Home/HomeFilterViewController.swift, MMM/Sources/ViewController/Home/HomeViewController.swift, MMM/Sources/ViewController/Home/Views/HomeHeaderStackView.swift, MMM/Sources/ViewController/HomeDetail/DetailViewController.swift, MMM/Sources/ViewController/Profile/ProfileViewController.swift, MMM/Sources/ViewController/Statistics/StatisticsViewController.swift, MMM/Sources/ViewController/Statistics/Views/StatisticsActivityView.swift, MMM/Sources/ViewController/Statistics/Views/StatisticsCategoryView.swift, MMM/Sources/ViewController/Statistics/Views/StatisticsTitleView.swift, MMM/Sources/ViewController/TabBar/TabBarController.swift
🌱 작업한 내용
- Home 로딩 제거
- 스켈레톤 View 제거
- Resolved: #153
=> [Style] Remove Skeleton

MMM.xcodeproj/project.pbxproj, MMM/App/AppDelegate.swift, MMM/App/SceneDelegate.swift, MMM/Sources/Services/Network/AppstoreCheck.swift, MMM/Sources/Utilities/AppstoreCheck.swift, MMM/Sources/ViewController/Profile/Views/ProfileFooterView.swift
=> [Feat] 앱 버전 관리 

MMM/Sources/ViewController/ETC./BottomPageControlView2.swift, MMM/Sources/ViewController/HomeDetail/DetailViewController.swift, MMM/Sources/ViewController/HomeDetail/DetailViewController2.swift
=> [Feat] swipe 기능 추가 및 index 오류 해결

MMM.xcodeproj/project.pbxproj, MMM/Sources/ViewController/CategoryEdit/CategoryEditViewController.swift, MMM/Sources/ViewController/CategoryEdit/Views/CategoryEditSectionFooter.swift
🌱 작업한 내용
- 앱이 꺼지는 문제 - Caterory edit의 Out of index 해결
- Resolved: #165
=> [Fix] 앱이 꺼지는 문제 - Caterory edit의 Out of index 해결

MMM/Resources/Base/BaseAddActivityViewController.swift, MMM/Resources/Extensions/Ex+UIImageView.swift, MMM/Sources/ViewController/HomeDetail/DetailViewController.swift, MMM/Sources/ViewController/HomeDetail/Edit/EditActivityViewController.swift
=> [Feat] 카메라 선택접근 오류 개선

MMM/Sources/Reactor/StatisticsReactor.swift, MMM/Sources/ViewController/Statistics/StatisticsViewController.swift, MMM/Sources/ViewController/Statistics/Views/StatisticsActivityView.swift, MMM/Sources/ViewController/Statistics/Views/StatisticsAverageView.swift
🌱 작업한 내용
- 예산 업데이트 2 - 요약보기/닫기
- Resolved: #
=> [Feat] 예산 업데이트 2 - 요약보기/닫기

MMM.xcodeproj/project.pbxproj, MMM/Resources/Extensions/UIKit/Ex+String.swift, MMM/Sources/Utilities/Text/ActionSheetText.swift, MMM/Sources/Utilities/Text/AlertText.swift, MMM/Sources/Utilities/Text/CommonText.swift, MMM/Sources/ViewController/BottomSheet/AddSchedule/AddScheduleView.swift, MMM/Sources/ViewController/BottomSheet/AddSchedule/CustomCalendarView.swift, MMM/Sources/ViewController/HomeDetail/Edit/EditActivityViewController.swift, MMM/Sources/ViewModels/EditActivityViewModel.swift
=> [Feat] 경제활동 반복 기능 추가
